version: 2

workflows:
  version: 2
  build_linux:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: nixos/nix:latest

    steps:
      - checkout
      - run: nix-build ./buildscripts/nixos_qtox.txt


