name: nixos build
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy
jobs:
  build-nixos:
    name: nixos
    if: ${{ false }}  # disable for now
    runs-on: nixos/nix
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Run build
        run: pwd;ls -al;nix-build ./buildscripts/nixos_qtox.txt
