name: nixos tests

on:
  push:
  pull_request:

jobs:
    compile:
        name: nixos test
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Run test
            uses: addnab/docker-run-action@v3
            with:
                image: nixos/nix:latest
                options: -v ${{ github.workspace }}:/work
                run: |
                    id;ls -al /work/; # compile command here
